CREATE TYPE USER_ROLE_ENUM AS ENUM ('client', 'admin');
ALTER TYPE USER_ROLE_ENUM OWNER TO pg;

ALTER TABLE "user" ALTER COLUMN role TYPE USER_ROLE_ENUM USING 'client'::USER_ROLE_ENUM;
ALTER TABLE "user" ALTER COLUMN role SET DEFAULT 'client'::USER_ROLE_ENUM;
ALTER TABLE "user" ALTER COLUMN role SET NOT NULL;