version: '3.8'

services:
  pg:
    image: 'postgres:latest'
    container_name: ${APP_NAME}-pg
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: 'redis:latest'
    container_name: ${APP_NAME}-redis
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
